//User Action

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

//User Update Profile Pic
export const FETCH_USER_UPDATE_PIC_REQUEST = 'FETCH_USER_UPDATE_PIC_REQUEST';
export const FETCH_USER_UPDATE_PIC_SUCCESS = 'FETCH_USER_UPDATE_PIC_SUCCESS';
export const FETCH_USER_UPDATE_PIC_ERROR = 'FETCH_USER_UPDATE_PIC_ERROR';

//User Remove Profile Pic
export const FETCH_USER_REMOVE_PIC_REQUEST = 'FETCH_USER_REMOVE_PIC_REQUEST';
export const FETCH_USER_REMOVE_PIC_SUCCESS = 'FETCH_USER_REMOVE_PIC_SUCCESS';
export const FETCH_USER_REMOVE_PIC_ERROR = 'FETCH_USER_REMOVE_PIC_ERROR';

//User Remove Profile Pic
export const FETCH_USER_REFRESH_REQUEST = 'FETCH_USER_REFRESH_REQUEST';
export const FETCH_USER_REFRESH_SUCCESS = 'FETCH_USER_REFRESH_SUCCESS';
export const FETCH_USER_REFRESH_ERROR = 'FETCH_USER_REFRESH_ERROR';


//Post Action//

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

//Like post Action//

export const FETCH_LIKE_POST_REQUEST = 'FETCH_LIKE_POST_REQUEST';
export const FETCH_LIKE_POST_SUCCESS = 'FETCH_LIKE_POST_SUCCESS';
export const FETCH_LIKE_POST_ERROR = 'FETCH_LIKE_POST_ERROR';

//Comments Action
export const FETCH_COMMENTS_POST_REQUEST = 'FETCH_COMMENTS_POST_REQUEST';
export const FETCH_COMMENTS_POST_SUCCESS = 'FETCH_COMMENTS_POST_SUCCESS';
export const FETCH_COMMENTS_POST_ERROR = 'FETCH_COMMENTS_POST_ERROR';
